# Copyright (C) 2020 The MoKee Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/meizu/sdm710-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/meizu/sdm710-common

PRODUCT_COPY_FILES += \
    vendor/meizu/sdm710-common/proprietary/etc/permissions/privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-qti.xml \
    vendor/meizu/sdm710-common/proprietary/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qcrilhook.xml \
    vendor/meizu/sdm710-common/proprietary/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_libpermissions.xml \
    vendor/meizu/sdm710-common/proprietary/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/qti_permissions.xml \
    vendor/meizu/sdm710-common/proprietary/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/telephonyservice.xml \
    vendor/meizu/sdm710-common/proprietary/etc/sysconfig/qti_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/qti_whitelist.xml \
    vendor/meizu/sdm710-common/proprietary/framework/QtiTelephonyServicelibrary.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/QtiTelephonyServicelibrary.jar \
    vendor/meizu/sdm710-common/proprietary/framework/qcrilhook.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/qcrilhook.jar \
    vendor/meizu/sdm710-common/proprietary/framework/qti-telephony-common.jar:$(TARGET_COPY_OUT_SYSTEM)/framework/qti-telephony-common.jar \
    vendor/meizu/sdm710-common/proprietary/lib/libFileMux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libFileMux.so \
    vendor/meizu/sdm710-common/proprietary/lib/libOmxMux.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libOmxMux.so \
    vendor/meizu/sdm710-common/proprietary/lib/libmmosal.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmosal.so \
    vendor/meizu/sdm710-common/proprietary/lib/libmmparser.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmparser.so \
    vendor/meizu/sdm710-common/proprietary/lib/libmmparser_lite.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmparser_lite.so \
    vendor/meizu/sdm710-common/proprietary/lib64/lib-imsvideocodec.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvideocodec.so \
    vendor/meizu/sdm710-common/proprietary/lib64/lib-imsvt.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvt.so \
    vendor/meizu/sdm710-common/proprietary/lib64/lib-imsvtextutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvtextutils.so \
    vendor/meizu/sdm710-common/proprietary/lib64/lib-imsvtutils.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/lib-imsvtutils.so \
    vendor/meizu/sdm710-common/proprietary/lib64/libdiag_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdiag_system.so \
    vendor/meizu/sdm710-common/proprietary/lib64/libimscamera_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimscamera_jni.so \
    vendor/meizu/sdm710-common/proprietary/lib64/libimsmedia_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimsmedia_jni.so \
    vendor/meizu/sdm710-common/proprietary/lib64/libmmosal.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libmmosal.so \
    vendor/meizu/sdm710-common/proprietary/lib64/librcc.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/librcc.so \
    vendor/meizu/sdm710-common/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/meizu/sdm710-common/proprietary/bin/hw/android.hardware.configstore@1.0-service:$(TARGET_COPY_OUT_SYSTEM)/bin/hw/android.hardware.configstore@1.0-service \
    vendor/meizu/sdm710-common/proprietary/bin/hw/android.hardware.drm@1.0-service.widevine:$(TARGET_COPY_OUT_SYSTEM)/bin/hw/android.hardware.drm@1.0-service.widevine \
    vendor/meizu/sdm710-common/proprietary/bin/hw/android.hardware.graphics.composer@2.1-service:$(TARGET_COPY_OUT_SYSTEM)/bin/hw/android.hardware.graphics.composer@2.1-service \
    vendor/meizu/sdm710-common/proprietary/bin/hw/android.hardware.media.omx@1.0-service:$(TARGET_COPY_OUT_SYSTEM)/bin/hw/android.hardware.media.omx@1.0-service \
    vendor/meizu/sdm710-common/proprietary/bin/hw/android.hardware.wifi@1.0-service:$(TARGET_COPY_OUT_SYSTEM)/bin/hw/android.hardware.wifi@1.0-service \
    vendor/meizu/sdm710-common/proprietary/bin/mm-pp-dpps:$(TARGET_COPY_OUT_SYSTEM)/bin/mm-pp-dpps \
    vendor/meizu/sdm710-common/proprietary/bin/pm-service:$(TARGET_COPY_OUT_SYSTEM)/bin/pm-service \
    vendor/meizu/sdm710-common/proprietary/bin/slim_daemon:$(TARGET_COPY_OUT_SYSTEM)/bin/slim_daemon \
    vendor/meizu/sdm710-common/proprietary/lib/hw/android.hardware.audio@2.0-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/android.hardware.audio@2.0-impl.so \
    vendor/meizu/sdm710-common/proprietary/lib/libmms_hal_vstab.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmms_hal_vstab.so \
    vendor/meizu/sdm710-common/proprietary/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/android.hardware.bluetooth@1.0-impl-qti.so \
    vendor/meizu/sdm710-common/proprietary/lib64/hw/android.hardware.graphics.composer@2.1-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/android.hardware.graphics.composer@2.1-impl.so \
    vendor/meizu/sdm710-common/proprietary/lib64/hw/android.hardware.sensors@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/android.hardware.sensors@1.0-impl.so \
    vendor/meizu/sdm710-common/proprietary/lib64/hw/vendor.qti.hardware.sensorscalibrate@1.0-impl.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/hw/vendor.qti.hardware.sensorscalibrate@1.0-impl.so \
    vendor/meizu/sdm710-common/proprietary/lib64/libhwminijail.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhwminijail.so \
    vendor/meizu/sdm710-common/proprietary/lib64/libsensorndkbridge.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libsensorndkbridge.so \
    vendor/meizu/sdm710-common/proprietary/lib64/vendor.qti.gnss@1.0_vendor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.qti.gnss@1.0_vendor.so

PRODUCT_PACKAGES += \
    QtiTelephonyService \
    ims \
    qcrilmsgtunnel
